### ISSUE TITLE
`lazygit.nvim` not updated

### ISSUE THREAD

**Issue by patrickaldis** [NixNeovim/NixNeovimPlugins#64]
Hi,

I'm just wondering why [lazygit.nvim](https://github.com/jesseduffield/lazygit/releases) plugin has not been updated since 2022.

There have been releases since then

**Comment by jooooscha** [comment]
Thanks for reporting.

I cannot be sure why this happens, currently. The main problem is that the update script is seriously broken and unfixable (for me).
I hope #54 will be ready soon.

Weirdly enough, I canont find lazygit.nvim in the logs of the update actions. I try to look into it, but do not have high hopes until #54 is ready.

Btw, you are linking lazygit, not lazygit.nvim.

**Comment by jooooscha** [comment]
I have just merged #71 (which replaced #54), I hope this solves your issue.

Please reopen, if something like this does occur again.
