### ISSUE TITLE
buildVimPluginFrom2Nix is deprecated

### ISSUE THREAD

**Issue by jalil-salame** [NixNeovim/NixNeovimPlugins#95]
As of 23.11 `buildVimPluginFrom2Nix` is [deprecated](https://nixos.org/manual/nixos/stable/release-notes#sec-release-23.11-nixos-breaking-changes). It has been renamed to `buildVimPlugin` and skips the `configurePhase` and `buildPhase`. This should speed up the building of plugins.

I would be willing to do this migration but I might need some help navigating the codebase.

Specifically, when I tried running `nix flake check` a bunch of plugins no longer exist so I might have trouble testing my changes

**Comment by jooooscha** [comment]
I noticed this when it first came up. The way to change this is to change the generation script that produces the nix code for the plugins. That's where the `buildVimPluginFrom2Nix` is used.
However, I had some problems with weird errors I wouldn't understand, so I gave up.

Maybe, it's worth looking at this again.

**Comment by jooooscha** [comment]
Ok, replaced all mentions of `buildVimPluginFrom2Nix` with `buildVimPlugin`. This time, I don't seem to have any errors.
Let's, see if everything still works after the next plugin update.

As for the speed up, at this point `buildVimPluginFrom2Nix` was an alias to `buildVimPlugin`, anyway. So I don't think there should be any difference.

Anyway, Thanks for taking your time to open this issue 👍
